// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgoIxqSn2uW6AzRvPjtZ0ZgwpT4rIjqBE',
    appId: '1:299083832021:web:9703321111a0f65b66205c',
    messagingSenderId: '299083832021',
    projectId: 'kaih-app',
    authDomain: 'kaih-app.firebaseapp.com',
    storageBucket: 'kaih-app.firebasestorage.app',
    measurementId: 'G-M9VBCN61MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6bwrQvl6jFgVH3D77VHKPMRDJ7_2J20',
    appId: '1:299083832021:android:364ed8b240d5c97366205c',
    messagingSenderId: '299083832021',
    projectId: 'kaih-app',
    storageBucket: 'kaih-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn0twAe42JKxPhNPxY9t-KVVkC31WpiBg',
    appId: '1:299083832021:ios:06f528acc984110566205c',
    messagingSenderId: '299083832021',
    projectId: 'kaih-app',
    storageBucket: 'kaih-app.firebasestorage.app',
    iosBundleId: 'com.example.kaih7Xirpl2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn0twAe42JKxPhNPxY9t-KVVkC31WpiBg',
    appId: '1:299083832021:ios:06f528acc984110566205c',
    messagingSenderId: '299083832021',
    projectId: 'kaih-app',
    storageBucket: 'kaih-app.firebasestorage.app',
    iosBundleId: 'com.example.kaih7Xirpl2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgoIxqSn2uW6AzRvPjtZ0ZgwpT4rIjqBE',
    appId: '1:299083832021:web:4752e0ee035c484566205c',
    messagingSenderId: '299083832021',
    projectId: 'kaih-app',
    authDomain: 'kaih-app.firebaseapp.com',
    storageBucket: 'kaih-app.firebasestorage.app',
    measurementId: 'G-14ZYEP1THM',
  );

}